server:
  port: 8002
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bqx?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  application:
    name: community-server

logging:
  config: classpath:logging-config.xml
  level:
    com.bqx.community.mapper: info