server:
  port: 8081
logging:
  config: classpath:logging-config.xml
  level:
    com.bqx.community.mapper: info

spring:
  profiles:
    active: dev
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: elasticsearch
