server:
  port: 8002
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.tianlongfightclub.com:3306/rpo?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: admin
    password: 123456
  application:
    name: community-server
  mvc:
    servlet:
      load-on-startup: 100
logging:
  config: classpath:logging-config.xml
  level:
    root: info

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
